---
abstract: 'A Moose role for processing command line options'
author:
  - 'Stevan Little <stevan@iinteractive.com>'
build_requires:
  Test::Exception: 0.21
  Test::More: 0.62
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: MooseX-Getopt
no_index:
  directory:
    - inc
    - t
requires:
  Getopt::Long: 2.37
  Getopt::Long::Descriptive: 0
  Moose: 0.43
version: 0.15
