---
abstract: 'A Moose role for processing command line options'
author:
  - 'Stevan Little <stevan@iinteractive.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Exception: 0.21
  Test::Moose: 0
  Test::More: 0.62
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.910'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-Getopt
no_index:
  directory:
    - inc
    - t
requires:
  Getopt::Long: 2.37
  Getopt::Long::Descriptive: 0
  Moose: 0.56
resources:
  license: http://dev.perl.org/licenses/
  repository: git://git.moose.perl.org/MooseX-Getopt.git
version: 0.21
